name: Deploy Java app to AWS Lambda

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Project
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'  

      - name: Upload JAR file to AWS Lambda
        run: lambda update-function --function-name HandlerString --zip-file fileb://target/lambda-basic-1.0-SNAPSHOT.jar
